### ISSUE TITLE
Type mismatch in CourseList

### ISSUE THREAD

**Issue by xuxey** [open-source-at-illinois/cherry#16]
Looks like there's a string/int type mismatch when using `row.gpa` in CourseList
![image](https://user-images.githubusercontent.com/45848414/141018019-ab1874ab-1680-4cb1-943c-e74d4103c8f3.png)

**Comment by xuxey** [comment]
Remember to pull changes before fixing this :)

**Comment by arniboy4** [comment]
I am working on it!
