### ISSUE TITLE
Remove wave footer from mobile screens

### ISSUE THREAD

**Issue by xuxey** [open-source-at-illinois/cherry#46]
The wave footer created using `<div className="spacer curve1"></div>` in `index.js` renders weirdly on mobile screens, would be best to remove it altogether from smaller screens

**Comment by RishiKumarRay** [comment]
@xuxey do we have to just remove this or anything else needs to be done also?

**Comment by faddock** [comment]
@RishiKumarRay the footer needs to be removed in only the mobile view

**Comment by xuxey** [comment]
Just need to remove this when screen width is <900px. I'd like to leave it as-is on desktop
